@startuml hub_resource
!theme mars
skinparam NoteFontName Courier

actor Client as client
boundary API as api

client -> api++: GET /
return 200 OK
note left
{
  "_links": {
    "user": {
      "href": "https://example.com/users/123456"
    },
<color:red>    "order-history": {
<color:red>      "href": "https://example.com/orders?user_id=123456"
<color:red>    }
  }
}
endnote

client -> api++: GET *order-history
return 200 OK
@enduml
