@startuml overlay_resource
!theme mars
skinparam NoteFontName Courier

actor Client as client
boundary API as api

client -> api++: GET /products
return 200 OK
note left
{
  "_embedded": {
    "items": [
      {
        "name": "Super Widget",
        "price": {
          "amount": 30,
          "currency": "EUR"
        },
        "_links": {
          <color:red>"self": {
          <color:red>  "href": "https://example.com/super-widget"
          <color:red>}
        }
      },
      {
        "name": "Widget 3000",
        "price": {
          "amount": 15,
          "currency": "EUR"
        },
        "_links": {
          self: {
            "href": "https://example.com/widget-3000"
          }
        }
      }
    ],
  },
  "_links": {
<color:red>    "historic-price": {
<color:red>      "href": "https://example.com/price-history?product=super-widget&product=widget-3000&at=2023-04-22T15:46:00Z"
<color:red>    }
  }
}
endnote

client -> api++: GET *historic-price
return 200 OK
note left
{
  "_embedded": {
    "items": [
      {
        "price": {
          "amount": 35,
          "currency": "EUR"
        },
        "_links": {
<color:red>          "product": {
<color:red>            "href": "https://example.com/super-widget"
<color:red>          }
        }
      },
      {
        "price": {
          "amount": 12,
          "currency": "EUR"
        },
        "_links": {
          "product": {
            "href": "https://example.com/widget-3000"
          }
        }
      }
    ]
  }
}
endnote
@enduml
